version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.1
  - dependency-name: oj
    versions:
    - 3.11.4
  - dependency-name: connection_pool
    versions:
    - 2.2.4
  - dependency-name: semantic_range
    versions:
    - 3.0.0
  - dependency-name: paper_trail
    versions:
    - 12.0.0
  - dependency-name: mimemagic
    versions:
    - 0.3.10
    - 0.3.6
    - 0.3.7
    - 0.3.8
    - 0.3.9
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: oauth2
    versions:
    - 1.4.6
  - dependency-name: nokogiri
    versions:
    - 1.11.2
  - dependency-name: nio4r
    versions:
    - 2.5.6
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
  - dependency-name: i18n
    versions:
    - 1.8.9
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: capybara
    versions:
    - 3.35.2
  - dependency-name: msgpack
    versions:
    - 1.4.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.3
    - 6.3.0
    - 6.3.2
    - 6.3.3
  - dependency-name: "@github/hotkey"
    versions:
    - 1.4.3
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.2
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.2
