AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
