language: ruby
cache: bundler
services:
  - postgresql
  - redis-server
rvm:
  - 2.6.3
before_install:
  - echo "APT::Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
  - sudo apt-get update
  - sudo apt-get remove -y postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
install:
  - gem update --system
  - gem install bundler
  - bundle install --deployment --jobs 4 --retry 3
  - bin/yarn install --non-interactive --network-concurrency 4 --network-timeout 5000
before_script:
  - psql -c 'create database roombooking_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:schema:load roombooking:search:setup
script:
  - RAILS_ENV=test bundle exec rake --trace test
addons:
  postgresql: "11.2"
branches:
  only:
  - master
