version: '3'
services:
  web: &base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      DOCKERIZED: 1
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:@db:5432
      REDIS_CACHE: redis://cache:6379/1
      REDIS_STORE: redis://cache:6379/1
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0
  worker:
    ports: []
    <<: *base
    command: bundle exec sidekiq
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: roombooking_development
  cache:
    image: redis
    ports:
      - "6379:6379"
