version: '3'
services:
  web: &base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    networks:
        - backend
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - cache
    environment:
      DATABASE_URL: postgres://postgres:@db:5432
      REDIS_CACHE: redis://cache:6379/1
      REDIS_STORE: redis://cache:6379/1
    command: bundle exec rails server -b 0.0.0.0
  worker:
    ports: []
    <<: *base
    command: bundle exec sidekiq
  db:
    image: postgres
    networks:
        - backend
    environment:
      POSTGRES_DB: roombooking_development
  cache:
    image: redis
    networks:
        - backend
networks:
  backend:
    driver: bridge
