Email verification reminder job:
  cron: '0 3 * * *'
  class: 'EmailVerificationReminderJob'
  queue: 'roombooking_jobs'

Sitemap generation job:
  cron: '0 4 * * *'
  class: 'SitemapGenerationJob'
  queue: 'roombooking_jobs'

Camdram API access token refresh job:
  cron: '*/5 * * * *'
  class: 'CamdramTokenRefreshJob'
  queue: 'roombooking_jobs'

Camdram API cache refresh job:
  cron: '*/15 * * * *'
  class: 'CamdramEntityRefreshJob'
  queue: 'roombooking_jobs'
