Approval reminder generator:
  cron: '0 10 * * *'
  class: 'ApprovalReminderJob'
  queue: 'jobs'

Sitemap generator:
  cron: '0 4 * * *'
  class: 'SitemapGenerationJob'
  queue: 'jobs'

Camdram API access token housekeeping:
  cron: '*/5 * * * *'
  class: 'HousekeepingJob'
  queue: 'jobs'
