---
<%
require 'dotenv'
Dotenv.load
%>

:concurrency: <%= (ENV['RAILS_ENV'] == 'production' && 2) || ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
:queues:
  - [roombooking_jobs, 2]
  - [roombooking_mail, 1]
  - [roombooking_exceptions, 1]
