name: Continuous integration and deployment

on:
  push:
    branches:
    - master

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build application stack
      run: docker-compose build
    - name: Configure environment 
      run: |
        rm -f .env
        echo "RAILS_ENV=test" >> .env
        echo "RAILS_MAX_THREADS=1" >> .env
        echo "WEB_CONCURRENCY=1" >> .env
        echo "SITE_HOSTNAME=roombooking-dev.adctheatre.com" >> .env
        echo "REDIS_CACHE=redis://127.0.0.1:6379/1" >> .env
        echo "REDIS_STORE=redis://127.0.0.1:6379/1" >> .env
        echo "CAMDRAM_APP_ID=${{ secrets.CAMDRAM_APP_ID }}" >> .env
        echo "CAMDRAM_APP_SECRET=${{ secrets.CAMDRAM_APP_SECRET }}" >> .env
        echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> .env
        docker-compose run --rm web "bundle exec rails roombooking:docker"
    - name: Run tests
      run: docker-compose run --rm web "bundle exec rails test"
