name: Continuous integration and deployment

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Setup Postgres 11
      uses: docker://postgres:11-alpine
    - name: Setup Redis
      uses: docker://redis:5-alpine
    - name: Install dependencies
      run: |
        gem update --system
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/yarn install --non-interactive --network-concurrency 4 --network-timeout 5000
    - name: Pre-flight checks
      run: |
        psql -c 'create database roombooking_test;' -U postgres
        export RAILS_ENV=test
        export RAILS_MAX_THREADS=1
        export WEB_CONCURRENCY=1
        export SITE_HOSTNAME=roombooking-dev.adctheatre.com
        export CAMDRAM_APP_ID=${{ secrets.CAMDRAM_APP_ID }}
        export CAMDRAM_APP_SECRET=${{ secrets.CAMDRAM_APP_SECRET }}
        export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
        export REDIS_CACHE=redis://127.0.0.1:6379/1
        export REDIS_STORE=redis://127.0.0.1:6379/1
        bundle exec rake --trace db:schema:load roombooking:search:setup
    - name: Run tests
      run: bundle exec rake --trace test
